
export const GET_USER = 'GET_USER';
export const GET_TRACKS = 'GET_TRACKS';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_PLAYLIST = 'REMOVE_FROM_PLAYLIST';
export const LOADING = 'LOADING';
export const TOGGLE_SIDEMENU = 'TOGGLE_SIDEMENU';
export const PREVIEW_SONG = 'PREVIEW_SONG';